---
- hosts: '{{ group }}'
  become_user: root
  become: true
  tasks:
  - name: install qemu-kvm package, libvirt, and virt-manager
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - qemu-kvm
      - libvirt-bin
      - virt-manager
      - virtinst

  - name: Display VMs running #should run without error
    virt: command=list_vms
    register: vm_list

  - name: Create a VM
    command: virt-install -n {{ vm_name }} -r {{ vm_ram }} \
             --disk path=/var/lib/libvirt/images/{{ vm_name }}.img,bus=virtio,size={{ vm_storage }} \
             -c {{ image_name }} --network network=default,model=virtio \
             --os-type={{ vm_os_type }} --os-variant={{ vm_os_variant }}  \
             --graphics vnc,listen=0.0.0.0 --noautoconsole -v
...
